config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  concern :votable do
    resources :votes, only: [] do
      collection do
        post :upvote
        post :downvote
        delete :resetvote
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :questions, concerns: [:votable,:commentable] do
    resources :answers, concerns: [:votable,:commentable], shallow: true do
      get :accept, on: :member
    end
  end

  resources :users, only: [] do
    collection do
      post 'require_email_for_auth'
    end
  end

  resources :attachments, only: [:destroy]

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Attachable
  include Votable
  include Commentable
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, :body, :user_id, presence: true
  validates :body, length: { minimum: 15 }

  scope :latest, -> { order(updated_at: :desc) }
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question
  end

  def create
    respond_with(@question = Question.create(question_params.merge(user: current_resource_owner)))
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: [:show]
  after_action :publish_question, only: [:create]

  respond_to :json, only: :create

  authorize_resource

  def index
    respond_with( @questions = Question.all )
  end

  def show
    @answer.attachments.build
    respond_with @question
  end

  def edit
  end

  def new
    @question = Question.new
    @question.attachments.build
    respond_with @question
  end

  def create
    respond_with(@question = Question.create(question_params.merge(user: current_user)))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/compact_view',
        locals: { q: @question }
      )
    )
  end

  def build_answer
    @answer = @question.answers.build
  end

  def find_question
    @question = Question.find(params[:id])
    gon.question_id = @question.id
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_attachment_fields.html.slim
.nested-fields
  - attachment = f.object
  - if attachment.new_record?
    = f.label :file
    = f.file_field :file
  - else
    = link_to attachment.file.filename, attachment.file_url
  p = link_to_remove_association "remove file", f

app/views/questions/_compact_view.html.slim
.demo-card-event.mdl-card.mdl-shadow--2dp
  .mdl-card__title
    .card_counter.rating id="#{q.id}-rating" = q.rating
    .mdl-tooltip data-mdl-for="#{q.id}-rating"
      | Rating
    .card_counter.answers id="#{q.id}-answers" = q.answers.count
    .mdl-tooltip data-mdl-for="#{q.id}-answers"
      | Answers
    h4 
      = link_to q.title, q
  .mdl-card__actions.mdl-card--border
    .mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect
      i.material-icons keyboard_arrow_up
    .mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect
      i.material-icons keyboard_arrow_down
    a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect
      | Answer

app/views/questions/edit.html.slim
h3 Edit question

= form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  
  p= f.submit 'Save'

app/views/questions/index.html.slim
.compact-questions-list
  - @questions.latest.each do |q|
    = render "questions/compact_view", q: q

app/views/questions/new.html.slim
= form_for(@question) do |f|
  h1  Title:
  p
    = f.label :title
    = f.text_field :title, placeholder: "New title"
  h1 Text:
  p 
    = f.label :body
    = f.text_area(:body, cols: 100, rows: 10)
    = render "attachments/edit", f: f
  p 
    = f.submit "Post Your Question"

app/views/questions/show.html.slim
.question-title
  h2 = @question.title
hr

.question-errors

.question-rating
  p Rating: #{@question.rating}
- if can?(:vote, @question)
  p = link_to 'upvote', upvote_question_votes_path(@question), method: :post, remote: true, class: 'vote-question-link', data: { type: :json }
  p = link_to 'downvote', downvote_question_votes_path(@question), method: :post, remote: true, class: 'vote-question-link', data: { type: :json }
  p = link_to 'reset', resetvote_question_votes_path(@question), method: :delete, remote: true, class: 'vote-question-link', data: { type: :json }

.question-body
  p = @question.body
= render "attachments/show", obj: @question
= render "layouts/user_info", obj: @question
- if can?(:destroy, @question)
  p = link_to 'delete', @question, class: 'delete-question-link', :method => :delete, :data => {:confirm => 'This will delete your question. Are you sure?'}
- if can?(:update, @question)
  p = link_to 'edit', '', class: 'edit-question-link'
  .question-errors
  p = form_for @question, remote: true, class:'edit_question' do |f|
    br
    = f.text_field :title
    br
    = f.text_area(:body, cols: 100, rows: 10)
    = render 'attachments/edit', f: f
    = f.submit 'Save'
br
= render "comments/comments", commentable: @question
br
hr
= render 'answers/answers'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.question-title').find("h2").html("<%= @question.title %>");
  $('.question-body').find("p").html("<%= @question.body %>");
  $('.question-attachments .show-attachments').html("<%= j render partial: 'attachments/show', locals: { obj: @question }  %>");
  $('.edit_question').hide();
  $('.edit-question-link').show();
<% end %>