config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  concern :votable do
    resources :votes, only: [] do
      collection do
        post :upvote
        post :downvote
        delete :resetvote
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :questions, concerns: [:votable,:commentable] do
    resources :answers, concerns: [:votable,:commentable], shallow: true do
      get :accept, on: :member
    end
  end

  resources :users, only: [] do
    collection do
      post 'require_email_for_auth'
    end
  end

  resources :attachments, only: [:destroy]

  mount ActionCable.server => '/cable'
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, optional: true, polymorphic: true

  mount_uploader :file, FileUploader
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  load_and_authorize_resource

  respond_to :js

  def destroy
    respond_with(@attachment.destroy)
  end

  private

  def attachment_params
    params.require(:id)
  end
end

app/views/attachments/_edit.html.slim
p Attachments:
p 
= f.fields_for :attachments do |a|
  = render 'attachments/fields', f: a
.links
  = link_to_add_association 'add file', f, :attachments, 
  partial: 'attachments/fields'

app/views/attachments/_fields.html.slim
.nested-fields
  - attachment = f.object
  - if attachment.new_record?
    = f.label :file
    = f.file_field :file
  - else
    = link_to attachment.file.identifier, attachment.file.url
  p = link_to_remove_association "remove file", f

app/views/attachments/_show.html.slim
.show-attachments
  - if obj.attachments.any?
    p Attachments:
    ul 
      - obj.attachments.each do |a|
        li.inline(class="attachment-#{a.id}")
          .div style="display: inline-block" 
            = link_to a.file.identifier, a.file.url
            - if can?(:destroy, a)
              = link_to 'delete file', attachment_path(a), method: :delete, remote: true 
              .div(class="attachment-errors-#{a.id}")

app/views/attachments/destroy.js.erb
<% if @attachment.errors.present? %>
  <% @attachment.errors.full_messages.each do |message| %>
    $('.attachment-errors-'+'<%= @attachment.id %>').html('<%= j message %>');
  <% end %>
<% else %>
  // check how many attachments in this section
  if ($('.attachment-'+ '<%= @attachment.id %>').parent().children().size() == 1){
    // if it is the last one - remove whole section with attachments
    $('.attachment-'+ '<%= @attachment.id %>').parent().parent().remove();
  } else {
    // if there are any other - remove only this item from list
    $('.attachment-'+ '<%= @attachment.id %>').remove();
  }
<% end %>