config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  concern :votable do
    resources :votes, only: [] do
      collection do
        post :upvote
        post :downvote
        delete :resetvote
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :questions, concerns: [:votable,:commentable] do
    resources :answers, concerns: [:votable,:commentable], shallow: true do
      get :accept, on: :member
    end
  end

  resources :users, only: [] do
    collection do
      post 'require_email_for_auth'
    end
  end

  resources :attachments, only: [:destroy]

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  belongs_to :user
  belongs_to :question

  validates :body,:user_id, presence: true

  default_scope { order(accepted: :desc) }

  def mark_as_accepted
    Answer.transaction do
      question.answers.update_all(accepted:false)
      raise ActiveRecord::Rollback unless question.answers.where(accepted: true).first.nil?
      update(accepted:true)
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :update]
  before_action :find_answer, only: [:destroy, :update, :accept]
  before_action :find_question, only: :create
  after_action :publish_answer, only: [:create]

  respond_to :js
  respond_to :json, only: :create

  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_user)))
  end

  def accept
    @answer.mark_as_accepted
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
      "question-#{@answer.question.id}-answers",
      rendering_params
    )
  end

  def rendering_params
    gon.question_author_id = @answer.question.user_id
    return @answer.as_json.merge(
      rating: @answer.rating,
      user: @answer.user.to_json,
      attachments: @answer.attachments.to_json,
    ).to_json
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end

  def find_question
    @question = @answer.nil? ? Question.find(params[:question_id]) : @answer.question
  end

  def find_answer
    @answer = Answer.find(params[:id])
    find_question
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:index, :create]

  authorize_resource

  def index
    @answers = @question.answers
    respond_with @answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_resource_owner)))
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .answer id="answer-#{answer.id}"
    .voting
      .errors
      .rating
        p Rating: #{answer.rating}
      - if can?(:vote, answer)
        p = link_to 'upvote', upvote_answer_votes_path(answer), method: :post, remote: true, class: 'vote-answer-link', data: { type: :json }
        p = link_to 'downvote', downvote_answer_votes_path(answer), method: :post, remote: true, class: 'vote-answer-link', data: { type: :json }
        p = link_to 'reset', resetvote_answer_votes_path(answer), method: :delete, remote: true, class: 'vote-answer-link', data: { type: :json }
    .votecell
      - if can?(:accept, answer)
        - if answer.accepted?
          = link_to(image_tag('accepted', size: "40x40", class: "accepted-icon"), accept_answer_path(answer), remote: true, class: 'accepted-link')
        - else
          = link_to(image_tag('accept', size: "40x40", class: "accept-icon"), accept_answer_path(answer), remote: true, class: 'accept-link')
      - elsif answer.accepted?
        = image_tag 'accepted', size: "40x40", class: "accepted-icon"
    br
    .answer-body = answer.body
    = render "attachments/show", obj: answer
    = render "layouts/user_info", obj: answer
    = render "comments/comments", commentable: answer
    
    - if can?(:destroy, answer)
      p = link_to 'delete', answer, class: 'delete-answer-link',
        method: :delete, remote: true, data: { confirm: "This will delete your answer #{answer.id}. Continue?" }
    - if can?(:update, answer)
      p = link_to 'edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
      br
      p = form_for answer, remote: true, html: {id: "edit-answer-#{answer.id}"} do |f|
        = f.label :body, 'Answer'
        br
        = f.text_area(:body, cols: 80, rows: 7)
        br
        = render 'attachments/edit', f: f
        = f.submit 'Save'
    hr

app/views/answers/_answers.html.slim
.answers
  - unless @question.answers.empty?
    h3 id="answers-label" Answers:
    = render @question.answers
  - else
    h3 id="answers-label" No answers so far
  .add-answer-form
    - if can?(:create, Answer)
      p = form_for [@question, @question.answers.build], remote: true do |f|
        = f.label 'Add your answer'
        .answer-errors
        = f.text_area(:body, cols: 80, rows: 7) 
        = render 'attachments/edit', f: f
        = f.submit "Post Your Answer", class: "button mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
    - else
      h4 You need to login to answer the question

app/views/answers/accept.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'answers' %>')
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('.new_answer').find("textarea").val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answer-<%= @answer.id %>').remove();
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answer-'+ '<%= @answer.id %>').find('.answer-body').html('<%= @answer.body %>');
  $('#answer-'+ '<%= @answer.id %>').find('.show-attachments').html("<%= j render partial: 'attachments/show', locals: { obj: @answer }  %>");
  $('form#edit-answer-' + '<%= @answer.id %>').hide();
  $('#answer-'+ '<%= @answer.id %>').find('.edit-answer-link').show();
<% end %>