config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  concern :votable do
    resources :votes, only: [] do
      collection do
        post :upvote
        post :downvote
        delete :resetvote
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :questions, concerns: [:votable,:commentable] do
    resources :answers, concerns: [:votable,:commentable], shallow: true do
      get :accept, on: :member
    end
  end

  resources :users, only: [] do
    collection do
      post 'require_email_for_auth'
    end
  end

  resources :attachments, only: [:destroy]

  mount ActionCable.server => '/cable'
end

app/views/layouts/_header.html.slim
header.mdl-layout__header
  .mdl-layout-icon
  .mdl-layout__header-row
    span.mdl-layout__title 
      = link_to "QNAPP", questions_path, class: "logo"
    .mdl-layout-spacer
    .qnapp-navigation.mdl-navigation
      = link_to "ASK QUESTION", new_question_path, class: "mdl-navigation__link"
      - if user_signed_in?
        = link_to "SIGN OUT", destroy_user_session_path(@user), method: :delete, class: "mdl-navigation__link"
      - else
        = link_to "SIGN UP", new_user_registration_path, class: "mdl-navigation__link"
        = link_to "SIGN IN", new_user_session_path, class: "mdl-navigation__link"

app/views/layouts/_user_info.html.slim
.user_info
  | Created #{obj.created_at.strftime("%d %b. %Y")}
  br
  | by #{obj.user.email}

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Qnapp"
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" 
    link href="https://code.getmdl.io/1.3.0/material.light_green-yellow.min.css" rel="stylesheet"
    script defer="" src="https://code.getmdl.io/1.3.0/material.min.js" 
  
    = include_gon
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = action_cable_meta_tag
    = javascript_include_tag "application"

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body
    .mdl-layout.mdl-js-layout
      = render 'layouts/header'
      main.mdl-layout__content
        .centered-container
          = bootstrap_flash
          = yield